import { Dimensions, StyleSheet } from 'react-native';
import { colors } from '../../style/colors';
import { radii, spacing } from '../../style/spacing';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    paddingBottom: spacing.xxl,
  },
  coverImage: {
    width: '100%',
    height: Math.min(210, width * 0.52),
    backgroundColor: colors.border,
  },
  section: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
  },
  chipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  statusChip: {
    backgroundColor: '#FFF4D7',
    borderRadius: radii.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
  },
  statusText: {
    color: '#B45309',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  categoryChip: {
    backgroundColor: colors.secondary,
    borderRadius: radii.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
  },
  categoryText: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '700',
  },
  title: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 6,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: spacing.md,
  },
  metaText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  metaDot: {
    color: colors.textSecondary,
    fontSize: 12,
    paddingHorizontal: 6,
  },
  description: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 21,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: spacing.sm,
  },
  mapPreview: {
    height: 180,
    borderRadius: radii.lg,
    overflow: 'hidden',
    backgroundColor: colors.border,
    marginTop: spacing.xs,
  },
  map: {
    flex: 1,
  },
  mapUnavailable: {
    minHeight: 96,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    padding: spacing.md,
  },
  mapUnavailableText: {
    color: colors.textSecondary,
    fontSize: 13,
    textAlign: 'center',
  },
  actionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  countButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  countText: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  shareButton: {
    marginLeft: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surface,
  },
  shareText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '600',
  },
  supportButton: {
    marginHorizontal: spacing.md,
    marginTop: spacing.md,
    height: 50,
    borderRadius: radii.pill,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.22,
    shadowRadius: 9,
    elevation: 3,
  },
  supportText: {
    color: colors.surface,
    fontSize: 15,
    fontWeight: '800',
  },
  finalizeButton: {
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
    minHeight: 48,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  finalizeButtonDisabled: {
    opacity: 0.7,
  },
  finalizeText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '800',
  },
  commentCard: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  commentsState: {
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  commentsStateText: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  avatarImage: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: colors.border,
  },
  avatarInitials: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.secondary,
  },
  avatarInitialsText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
  },
  commentBubble: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  commentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  commentAuthor: {
    flex: 1,
    color: colors.text,
    fontSize: 12,
    fontWeight: '800',
  },
  commentTime: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  commentText: {
    color: colors.text,
    fontSize: 13,
    lineHeight: 18,
  },
  commentActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  commentIconButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 30,
    paddingHorizontal: spacing.sm,
    borderRadius: radii.pill,
    backgroundColor: colors.background,
  },
  commentIconButtonText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '700',
  },
  commentIconButtonDangerText: {
    color: colors.error,
  },
  editCommentInput: {
    minHeight: 72,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    color: colors.text,
    fontSize: 13,
    lineHeight: 18,
    padding: spacing.sm,
    textAlignVertical: 'top',
  },
  commentTextButton: {
    minHeight: 34,
    paddingHorizontal: spacing.md,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  commentTextButtonPrimary: {
    minWidth: 76,
    backgroundColor: colors.primary,
  },
  commentTextButtonLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  commentTextButtonPrimaryLabel: {
    color: colors.surface,
    fontSize: 12,
    fontWeight: '800',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  commentInput: {
    flex: 1,
    minHeight: 40,
    maxHeight: 92,
    borderRadius: radii.pill,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    color: colors.text,
    fontSize: 13,
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendButtonActive: {
    backgroundColor: colors.primary,
  },
});
